version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    # definindo aonde esta as variaveis de ambiente
    env_file:
      - ./env.dev
    networks:
      - backend
    # dependencia para esta aplicação
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgres/data/
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=bookstore_db
    networks:
      - backend
networks:
  backend:
    driver: bridge

volumes:
  postgres_data:

  
